# Project information
site_name: ImJoy demo project
site_description: Demonstrating how to create an ImJoy project
site_author: Florian MUELLER
site_url: https://muellerflorian.github.io/ImJoy-demo-project/

# Repository
repo_name: GitHub
repo_url: https://github.com/muellerflorian/ImJoy-demo-project
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2019 Florian MUELLER'


# Configuration
theme:
  name: 'material'
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /img/icons8-eukaryotic-cells-filled-100.png
  logo:
    icon: wb_sunny

# Customization
markdown_extensions:
  - toc:
        permalink: true   # Adds anchor at the end of each headline, to directly link to a subpart of the document: https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
  - codehilite     # adds syntax highlighting to code blocks: https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
  - admonition
  - pymdownx.superfences  # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/muellerflorian

nav:
    - Overview:  index.md  # Needed for material theme but not for others
    - 1. Code organization: code-organization.md
    - 2. GitHub: github.md
    - 3. Documentation: documentation.md
    - 4. Python development: python-development.md
    - 5. ImJoy development: imjoy-development.md
    - 6. Deployment: deployment.md
    - 7. Distribution: distribution.md
